### ISSUE TITLE
in data dictionary change 'column_name' to 'name'

### ISSUE THREAD

**Issue by robcrystalornelas** [ess-dive-community/essdive-file-level-metadata#16]
***Term to change**: Which of the FLMD terms would you like to modify?
**Submitter**: Rob Crystal-Ornelas
**Justification**: Why is this change necessary? We may consider this change because people might want to provide either a column_name *or* a row_name in their data dictionary (e.g., Hydrologic Monitoring reporting format)

## I suggest the following changes (leave blank whatever would not change):
* Term name: name
* Definition of the term: Definition wouldn't change, but we would be more flexible in data dictionary and allow users to indicate either column name or row name
* Format of the term: 
* Additional Instructions (recommendations regarding content, etc.):
* Examples: 
* Refines (name of the broader term this term refines, if applicable):
* Replaces (name of the existing term that would be replaced by this term, if applicable): column_name

**Comment by tvelliquette** [comment]
@robcrystalornelas I did have this comment over in CSV on Issue #2 but it fits better here. This wording needs to be consistent throughout both (all) reporting formats.

Instead of "Field" the term "column" appears throughout the FLMD and dd instructions. Should I change column to field or should I change it to "column/row name"

**Comment by tvelliquette** [comment]
related to issue #13

**Comment by robcrystalornelas** [comment]
We have decided on `Column_or_Row_Name`
